### PR TITLE
add option to disable joining lines

### PR DESCRIPTION
**Pull request by stheine**
Hi,

I have seen that you didn't want to implement that extra option, so I did it and created the pull request. please think about making it part of your module to avoid having to keep the fork alive longer.

Regards
  Stefan Heine

### CODE REVIEW

**Comment by SBoudrias** [comment]
Anyway instead of having another option we could just take a sane default route for everyone.

I'm still unclear as to what your use case is. I read the issue you opened, but it's really unclear what the problem is.

**Comment by stheine** [comment]
Hi, the original issue is: I want the output in the original format, so the linebreaks not converted into '\n', but printed breaking the lines. since stringify-object doesn't do that and doesn't offer an option for this, we have decided to use a post-process step that converts '\n' back into a real linebreak after the stringify-object step. that worked fine until someone started printing out windows paths that might have the '\n' character combination. since after stringify-object, there is no way to determine if a '\n' originally came from a linebreak, or from a real '\n' inside the object, out post-process step failed (converted too many '\n' into linebreaks).
that's why I added the option to disable joining the lines initially, as that would simply give us the option to skip our post-process step.

**Comment by stheine** [comment]
Hi, any feedback on my pull request? I'd hope to see it in, but rejecting it is also fine - then I'd publish my version on npmjs.com - but I'd like to avoid this, if the functionality is showing up in your version.

Regards
  stheine

**Comment by SBoudrias** [comment]
@sindresorhus any opinion on this? I'm kind of in-between on that feature.

**Comment by sindresorhus** [comment]
Gonna pass on this. Out of scope for this module.

What you want is not valid JS:

```js
'line1
  line2'
```

**Comment by stheine** [comment]
> What you want is not valid JS:

I guess that was the whole purpose of this module... something more easy to read, without all the quotes and stuff that JSON brings.

anyway, thanks for the response. my forked module is now available at https://github.com/stheine/stringify-object and https://www.npmjs.com/package/@stheine/stringify-object .

**Pull request closed without merging**
