### PR TITLE
fixes #26

### LINKED ISSUE #26: returns `[object Object]` when a non-plain-object is stringified
The following code will reproduce the bug:

```js
function Foo() {
  this.aaa = 'bbb';
  this.ccc = 'ddd';
  this.eee = 'fff';
}

var actual = stringifyObject(new Foo(), {
  indent: '  ',
  singleQuotes: true
});
console.log(actual);
//=> '[object Object]'
```

PR forthcoming...

### PR DESCRIPTION
**Pull request by jonschlinkert**
stringify objects not created by the `Object` constructor.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The plain object check is intentional to prevent it to recurse into non-plain objects: https://github.com/yeoman/stringify-object/commit/cf47dee8a7ce2d1d23a7b2c4c1389ee8d30e4c89

Should probably rather be a circular check here: https://github.com/yeoman/stringify-object/commit/cf47dee8a7ce2d1d23a7b2c4c1389ee8d30e4c89#diff-168726dbe96b3ce427e7fedce31bb0bcR26 ?

**Comment by jonschlinkert** [comment]
sorry I didn't see this. I'll take another look.

**Comment by jonschlinkert** [comment]
actually I think we should be able to just do a simple in-place shallow clone on the object first, then we can add the plain-object check back. that will copy the own properties from a non-plain object to a new object so it will pass the plain-object check, right?

**Comment by jonschlinkert** [comment]
actually after looking at it again, I think the commit you referenced should just be reverted. Doing a plain-object check makes this useless on anything created by an constructor besides `Object`, like Vinyl files for instance.

**Pull request closed without merging**
