### PR TITLE
Implements a configurable "one-liner" option

### PR DESCRIPTION
**Pull request by searls**
*(FYI: Submitting this separately from #30, since that hasn't been accepted yet and there is a merge conflict; to see the handled conflict check out how I [resolved the conflict](https://github.com/searls/stringify-object-with-one-liners/tree/47dcade8fafbe8adec95d4af005b561fb49cd6aa))*

This PR significantly increases the complexity of the module, and I would only recommend merging it if you believe it has general value. I'll plan on publishing my changes as a separate module.

For some cases, the added newlines & indents of short objects and arrays
makes the output unwieldy. This commit adds a new option
`inlineCharacterLimit`, which when set to a positive Number will
return stringified object or array that, with padding/indents/newlines
stripped would have a length less than `inlineCharacterLimit`.

As background, if I use stringify-object to print this argument list:

`foo(obj1, obj2)`

And `obj1` is `{a: 1, b: 2}` and `obj2` is `[1,2,3]`, and I try to
print a description of the invocation back to the user like this:

`'foo(' + stringifyObject(obj1) + ', ' + stringifyObject(obj2) + ')'`

Then what could be nice and terse as:

`'foo({a: 1, b: 2}, [1,2,3])'`

But will instead print something containing a lot of new lines, making
it hard to see the invocation being described.

I'm running into this a lot developing
https://github.com/testdouble/testdouble.js to have better output,
because using terse object and array params to pass to test doubles is
tremendously common, and I want to give users as best output as I can.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hey, sorry I forgot to review this and wasn't super active.

Anyway, just got the chance to go over it now and it seems good to me.

`stringify-object` doesn't have strong ownership within the yeoman team. I'll give you push/merge access if you would like to improve it further in the future.

**Comment by SBoudrias** [comment]
Well, actually there's a conflict now (with your other PR I believe). Feel free to fix and merge it.

**Comment by searls** [comment]
Cool. Done. How do you handle releases?

**Comment by SBoudrias** [comment]
@searls every time we merge a new feature/fix we usually bump a release :)

**Pull request merged**
